- hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: update

    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags: install

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes
      tags: start

    - name: Copy index.html
      copy:
        src: index1.html
        dest: /var/www/html/index.html
      tags: copy

    - name: Open HTTP port in UFW
      ufw:
        rule: allow
        port: 80
        proto: tcp
      tags: firewall
